# Generated by Django 5.0.3 on 2024-06-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardorderitems',
            name='Product_Quantity_IF_Default',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
