# Generated by Django 5.0.3 on 2024-06-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_cardorderitems_product_quantity_if_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardorderitems',
            name='total_price_for_MealAdditions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cardorderitems',
            name='total_price_for_MealSideDishes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cardorderitems',
            name='total_price_for_meal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
