# Generated by Django 5.0.3 on 2024-06-09 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productsoffers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsoffers',
            options={'verbose_name_plural': 'Products Offers'},
        ),
        migrations.RemoveField(
            model_name='offers',
            name='default',
        ),
    ]
