# Generated by Django 5.0.3 on 2024-05-31 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_offers_products_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='offer',
        ),
        migrations.AddField(
            model_name='products',
            name='offers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='product.offers'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='product_offers',
            field=models.CharField(choices=[('Default', 'Default'), ('Exclusive', 'Exclusive'), ('For 1 Person', 'For 1 Person'), ('Side dishes and desserts', 'Side dishes and desserts'), ('Beverages', 'Beverages')], default='processing', max_length=30),
        ),
    ]
