# Generated by Django 5.0.3 on 2024-06-09 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productsoffers_options_remove_offers_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='product',
        ),
    ]
