# Generated by Django 5.0.3 on 2024-06-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_cardorderitems_total_price_for_mealadditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardorderitems',
            name='MealAdditions',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='cardorderitems',
            name='MealSideDishes',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='cardorderitems',
            name='MealType',
            field=models.CharField(max_length=5000),
        ),
    ]
