# Generated by Django 5.0.3 on 2024-05-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_products_offer_products_offers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='product_offers',
            field=models.CharField(choices=[('Default', 'Default'), ('Exclusive', 'Exclusive'), ('For 1 Person', 'For 1 Person'), ('For Share', 'For Share'), ('Side dishes and desserts', 'Side dishes and desserts'), ('Beverages', 'Beverages')], default='processing', max_length=30),
        ),
    ]
