# Generated by Django 5.0.3 on 2024-05-31 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_offers_product_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to='global_categ/off/'),
        ),
    ]
