# Generated by Django 5.0.3 on 2024-06-07 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_cardorderitems_mealadditions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardorderitems',
            old_name='Product_Quantity_IF_Default',
            new_name='Product_Qu_Default',
        ),
    ]
