# Generated by Django 5.0.3 on 2024-06-09 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_offers_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsoffers',
            name='product_offers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProductsOffersProduct', to='product.offers'),
        ),
    ]
