# Generated by Django 5.0.3 on 2024-05-31 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_offers_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='image',
        ),
        migrations.AddField(
            model_name='offers',
            name='gallery_image',
            field=models.ImageField(default='product.jpg', upload_to='global_/off/'),
        ),
        migrations.AddField(
            model_name='offers',
            name='offer_image',
            field=models.ImageField(default='product.jpg', upload_to='off_/off/'),
        ),
    ]
