# Generated by Django 5.0.3 on 2024-06-09 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productsoffers_product_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardorderitems',
            name='product_offers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Products_Offers', to='product.offers'),
        ),
        migrations.AlterField(
            model_name='productsoffers',
            name='product_offers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProductsOffers', to='product.offers'),
        ),
    ]
