# Generated by Django 5.0.3 on 2024-06-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_product_quantity_if_default_cardorderitems_product_qu_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardorderitems',
            old_name='Product_Qu_Default',
            new_name='quantity',
        ),
    ]
