# Generated by Django 5.0.3 on 2024-06-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_product_qu_default_cardorderitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardorderitems',
            name='total_price_for_all',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cardorderitems',
            name='total_price_for_MealAdditions',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cardorderitems',
            name='total_price_for_MealSideDishes',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cardorderitems',
            name='total_price_for_meal',
            field=models.FloatField(default=0.0),
        ),
    ]
