# Generated by Django 5.0.3 on 2024-06-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_offers_image_offers_gallery_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='products',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='offers',
            name='product_offers',
            field=models.CharField(choices=[('Default', 'Default'), ('Exclusive', 'Exclusive'), ('For 1 Person', 'For 1 Person'), ('For Share', 'For Share'), ('Side dishes and desserts', 'Side dishes and desserts'), ('Beverages', 'Beverages')], default='Default', max_length=30),
        ),
    ]
