# Generated by Django 5.0.3 on 2024-06-09 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_cardorderitems_product_offers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsoffers',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Products_Offers_prod', to='product.products'),
        ),
    ]
