# Generated by Django 5.0.3 on 2024-06-05 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_products_tags_remove_products_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='digital',
        ),
        migrations.CreateModel(
            name='PRODUCT_Meal_TYPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_offers', models.CharField(choices=[('Normal', 'Normal'), ('Hot', 'Hot'), ('Mix', 'Mix')], default='Default', max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PRODUCT_Meal_TYPE', to='product.products')),
            ],
            options={
                'verbose_name_plural': 'PRODUCT Meal TYPE',
            },
        ),
        migrations.CreateModel(
            name='PRODUCT_SIDE_DISH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_offers', models.CharField(choices=[('Normal Sized Potatos', 'Normal Sized Potatos'), ('Coleslaw Salade', 'Coleslaw Salade'), ('Risotto', 'Risotto')], default='Default', max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PRODUCT_SIDE_DISH', to='product.products')),
            ],
            options={
                'verbose_name_plural': 'PRODUCT SIDE DISH',
            },
        ),
        migrations.CreateModel(
            name='PRODUCTS_additions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_offers', models.CharField(choices=[('Chicken Strips (Normal)', 'Chicken Strips (Normal)'), ('Chicken Strips (Spicy)', 'Chicken Strips (Spicy)'), ('lettuce', 'lettuce'), ('Tomato', 'Tomato'), ('American Cheese', 'American Cheese'), ('Smoked turkey', 'Smoked turkey')], default='Default', max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PRODUCTS_additions', to='product.products')),
            ],
            options={
                'verbose_name_plural': 'PRODUCTS additions',
            },
        ),
    ]
