# Generated by Django 5.0.3 on 2024-06-07 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_cardorderitems_total_price_for_all_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userordercard',
            name='uoc_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uoc_prod', to='product.products'),
        ),
    ]
