# Generated by Django 5.0.3 on 2024-06-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productsoffers_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardorderitems',
            name='checked_out_status',
            field=models.BooleanField(default=False),
        ),
    ]
