# Generated by Django 5.0.3 on 2024-06-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_userordercard_uoc_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardorderitems',
            name='MealAdditions',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='cardorderitems',
            name='MealSideDishes',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='cardorderitems',
            name='MealType',
            field=models.JSONField(),
        ),
    ]
