# Generated by Django 5.0.3 on 2024-06-05 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_products_digital_product_meal_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_meal_type',
            old_name='product_offers',
            new_name='product_Meal_TYPE',
        ),
        migrations.RenameField(
            model_name='product_side_dish',
            old_name='product_offers',
            new_name='product_SIDE_DISH',
        ),
        migrations.RenameField(
            model_name='products_additions',
            old_name='product_offers',
            new_name='product_additions',
        ),
    ]
