# Generated by Django 5.0.3 on 2024-06-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_cardorderitems_checked_out_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardorderitems',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
    ]
