# Generated by Django 5.0.3 on 2024-06-05 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_product_offers_product_meal_type_product_meal_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_side_dish',
            name='product',
        ),
        migrations.RemoveField(
            model_name='products_additions',
            name='product',
        ),
        migrations.CreateModel(
            name='ProductMealTYPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Meal_TYPE', models.CharField(choices=[('Normal', 'Normal'), ('Hot', 'Hot'), ('Mix', 'Mix')], default='Default', max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProductMealTYPE', to='product.products')),
            ],
            options={
                'verbose_name_plural': 'PRODUCT Meal TYPE',
            },
        ),
        migrations.CreateModel(
            name='ProductSideDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_SIDE_DISH', models.CharField(choices=[('Normal Sized Potatos', 'Normal Sized Potatos'), ('Coleslaw Salade', 'Coleslaw Salade'), ('Risotto', 'Risotto')], default='Default', max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProductSideDish', to='product.products')),
            ],
            options={
                'verbose_name_plural': 'PRODUCT SIDE DISH',
            },
        ),
        migrations.CreateModel(
            name='ProdutsAdditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_additions', models.CharField(choices=[('Chicken Strips (Normal)', 'Chicken Strips (Normal)'), ('Chicken Strips (Spicy)', 'Chicken Strips (Spicy)'), ('lettuce', 'lettuce'), ('Tomato', 'Tomato'), ('American Cheese', 'American Cheese'), ('Smoked turkey', 'Smoked turkey')], default='Default', max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProdutsAdditions', to='product.products')),
            ],
            options={
                'verbose_name_plural': 'PRODUCTS additions',
            },
        ),
        migrations.DeleteModel(
            name='PRODUCT_Meal_TYPE',
        ),
        migrations.DeleteModel(
            name='PRODUCT_SIDE_DISH',
        ),
        migrations.DeleteModel(
            name='PRODUCTS_additions',
        ),
    ]
