# Generated by Django 5.0.3 on 2024-06-22 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_cashiertable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiertable',
            name='SalesRep',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sale_rep', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashiertable',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
    ]
