# Generated by Django 5.0.3 on 2024-06-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product_side_dish_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmealtype',
            name='images',
            field=models.ImageField(default='product.jpg', upload_to='product-images/pmt'),
        ),
        migrations.AddField(
            model_name='productsidedish',
            name='images',
            field=models.ImageField(default='product.jpg', upload_to='product-images/psd'),
        ),
        migrations.AddField(
            model_name='produtsadditions',
            name='images',
            field=models.ImageField(default='product.jpg', upload_to='product-images/pa'),
        ),
    ]
