# Generated by Django 5.0.3 on 2024-06-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productmealtype_images_productsidedish_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmealtype',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmealtype',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmealtype',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='productsidedish',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productsidedish',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productsidedish',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='produtsadditions',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produtsadditions',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produtsadditions',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
