# Generated by Django 5.0.3 on 2024-06-22 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_cashiertable_salesrep_alter_cashiertable_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashiertable',
            name='SalesRep',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_rep', to=settings.AUTH_USER_MODEL),
        ),
    ]
