# Generated by Django 5.0.3 on 2024-06-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_productmealtype_default_productmealtype_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsidedish',
            name='product_SIDE_DISH',
            field=models.CharField(choices=[('Normal Sized Potatos', 'Normal Sized Potatos'), ('Coleslaw Salade', 'Coleslaw Salade'), ('Cheesy Fries', 'Cheesy Fries'), ('Cheesy Fries Halibeno', 'Cheesy Fries Halibeno'), ('Risotto', 'Risotto'), ('Potato Fries Fries', 'Potato Fries'), ('Double Potato Fries Fries', 'Double Potato Fries')], default='Default', max_length=30),
        ),
        migrations.AlterField(
            model_name='produtsadditions',
            name='product_additions',
            field=models.CharField(choices=[('Chicken Strips (Normal)', 'Chicken Strips (Normal)'), ('Chicken Strips (Spicy)', 'Chicken Strips (Spicy)'), ('lettuce', 'lettuce'), ('Tomato', 'Tomato'), ('American Cheese', 'American Cheese'), ('Smoked turkey', 'Smoked turkey'), ('Pickle', 'Pickle'), ('Garlicky', 'Garlicky')], default='Default', max_length=30),
        ),
    ]
