# Generated by Django 5.0.6 on 2024-06-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_cashiertable_salesrep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashiertable',
            name='client_number',
            field=models.CharField(max_length=50),
        ),
    ]
