# Generated by Django 5.0.3 on 2024-06-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_productsidedish_product_side_dish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmealtype',
            name='product_Meal_TYPE',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Hot', 'Hot'), ('Mix', 'Mix'), ('Single', 'Single'), ('Double', 'Double')], default='Default', max_length=30),
        ),
    ]
