# Generated by Django 5.0.3 on 2024-06-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_productmealtype_product_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsidedish',
            name='product_SIDE_DISH',
            field=models.CharField(choices=[('Normal Sized Potatos', 'Normal Sized Potatos'), ('Coleslaw Salade', 'Coleslaw Salade'), ('Cheesy Fries', 'Cheesy Fries'), ('Cheesy Fries Halibeno', 'Cheesy Fries Halibeno'), ('Risotto', 'Risotto'), ('Boom Frite Potato Fries', 'Boom Frite Potato Fries'), ('Double Boom Frite Potato Fries', 'Double Boom Frite Potato Fries')], default='Default', max_length=30),
        ),
    ]
