# Generated by Django 5.0.6 on 2024-06-30 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_cashiertable_client_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardorderitems',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
