# Generated by Django 5.0.6 on 2024-07-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_cardorderitems_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiertable',
            name='latitude',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='cashiertable',
            name='longitude',
            field=models.CharField(default=0.0, max_length=100),
        ),
    ]
