# Generated by Django 5.0.3 on 2024-06-06 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_productsidedish_product_side_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAdditionsNames',
            fields=[
                ('product_additions', models.CharField(default='Default', max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMealTypeNames',
            fields=[
                ('product_Meal_TYPE', models.CharField(default='Default', max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSideDishNames',
            fields=[
                ('product_SIDE_DISH', models.CharField(default='Default', max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='produtsadditions',
            name='product_additions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProdutsAdditions', to='product.productadditionsnames'),
        ),
        migrations.AlterField(
            model_name='productmealtype',
            name='product_Meal_TYPE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProductMealTYPE', to='product.productmealtypenames'),
        ),
        migrations.AlterField(
            model_name='productsidedish',
            name='product_SIDE_DISH',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProductSideDish', to='product.productsidedishnames'),
        ),
    ]
