# Generated by Django 5.0.3 on 2024-06-06 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_productadditionsnames_productmealtypenames_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffersNames',
            fields=[
                ('product_offers', models.CharField(default='Default', max_length=300, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='offers',
            name='product_offers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProductMealTYPE', to='product.offersnames'),
        ),
    ]
