# Generated by Django 5.0.6 on 2024-06-30 23:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_cashiertable_latitude_cashiertable_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offers',
            name='valid_for_today',
            field=models.BooleanField(default=False),
        ),
    ]
