# Generated by Django 5.0.3 on 2024-06-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_offersnames_alter_offers_product_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmealtype',
            name='images',
        ),
        migrations.RemoveField(
            model_name='productsidedish',
            name='images',
        ),
        migrations.RemoveField(
            model_name='produtsadditions',
            name='images',
        ),
        migrations.AddField(
            model_name='productadditionsnames',
            name='images',
            field=models.ImageField(default='product.jpg', upload_to='product-images/pa'),
        ),
        migrations.AddField(
            model_name='productmealtypenames',
            name='images',
            field=models.ImageField(default='product.jpg', upload_to='product-images/pmt'),
        ),
        migrations.AddField(
            model_name='productsidedishnames',
            name='images',
            field=models.ImageField(default='product.jpg', upload_to='product-images/psd'),
        ),
    ]
