# Generated by Django 5.0.6 on 2024-06-30 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_offers_created_at_offers_valid_for_today'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='created_at',
        ),
    ]
