# Generated by Django 5.0.6 on 2024-06-30 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_remove_offers_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 0, 0)),
        ),
    ]
