# Generated by Django 5.0.3 on 2024-06-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_remove_productadditionsnames_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmealtype',
            name='price',
        ),
        migrations.AddField(
            model_name='productmealtypenames',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
