# Generated by Django 5.0.3 on 2024-06-06 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_remove_productmealtype_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmealtype',
            name='images',
        ),
    ]
