# Generated by Django 5.0.6 on 2024-06-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_offers_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='offer_image_welcome',
            field=models.ImageField(default='product.jpg', upload_to='off_/welcome/'),
        ),
    ]
