# Generated by Django 5.0.6 on 2024-06-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_offers_offer_image_welcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='offer_image_welcome',
            field=models.ImageField(default='product.jpg', null=True, upload_to='off_/welcome/'),
        ),
    ]
