# Generated by Django 5.0.3 on 2024-06-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_productmealtype_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmealtypenames',
            name='images',
            field=models.ImageField(default='product.jpg', upload_to='product-images/pmt'),
        ),
    ]
