# Generated by Django 5.0.6 on 2024-07-03 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_offers_offer_image_welcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiertable',
            name='client_status_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
