# Generated by Django 5.0.3 on 2024-06-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_productmealtypenames_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsidedish',
            name='images',
        ),
        migrations.RemoveField(
            model_name='productsidedish',
            name='price',
        ),
        migrations.RemoveField(
            model_name='produtsadditions',
            name='images',
        ),
        migrations.RemoveField(
            model_name='produtsadditions',
            name='price',
        ),
        migrations.AddField(
            model_name='productadditionsnames',
            name='images',
            field=models.ImageField(default='product.jpg', upload_to='product-images/pa'),
        ),
        migrations.AddField(
            model_name='productadditionsnames',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='productsidedishnames',
            name='images',
            field=models.ImageField(default='product.jpg', upload_to='product-images/psd'),
        ),
        migrations.AddField(
            model_name='productsidedishnames',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
