# Generated by Django 5.0.3 on 2024-06-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_remove_productsidedish_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmealtypenames',
            name='price',
        ),
        migrations.AddField(
            model_name='productmealtype',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
