# Generated by Django 5.0.3 on 2024-06-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_remove_productmealtypenames_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmealtypenames',
            name='images',
        ),
        migrations.AddField(
            model_name='productmealtype',
            name='images',
            field=models.ImageField(default='product.jpg', upload_to='product-images/pmt'),
        ),
    ]
