# Generated by Django 5.0.3 on 2024-06-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_alter_usertoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Address',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='user',
            name='client_status',
            field=models.CharField(choices=[('Client', 'Client'), ('Cashier', 'Cashier'), ('Sales Representative', 'Sales Representative')], default='Client', max_length=30),
        ),
    ]
