# Generated by Django 5.0.6 on 2024-06-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_user_address_user_client_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_Number',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
