# Generated by Django 5.0.6 on 2024-06-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_alter_user_address_alter_user_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Address',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_Number',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
